- name: install ansible-rulebook
  hosts: all
  gather_facts: true
  vars:
    # TODO: remove token refs when repos are public
    github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
  tasks:
    - name: Ensure system dependencies
      become: true
      ansible.builtin.dnf:
        name:
          - git
          - python3
          - python3-pip
          - python3-devel
          - java-17-openjdk-devel
          - maven
          - gcc

    - name: set global envvars
      become: true
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}" 
      loop:
        - regexp: '^JAVA_HOME'
          line: JAVA_HOME=/usr/lib/jvm/java-17-openjdk
        - regexp: '^RULES_ENGINE'
          line: RULES_ENGINE=drools

    - name: Upgrade pip
      ansible.builtin.pip:
        name:
          - pip
        state: latest

    - name: Install pip dependencies
      ansible.builtin.pip:
        name:
          - ansible
          - ansible-runner
          - wheel
        state: latest

    - name: install ansible-rulebook
      environment:
        PIP_NO_BINARY: jpy
      ansible.builtin.pip:
        name: "git+https://{{ github_token }}@github.com/ansible/ansible-rulebook.git"
        state: forcereinstall

    - name: install collections
      command: ansible-galaxy collection install community.general ansible.eda 
    
        